use_frameworks!

platform :ios, '9.0'

target 'MKBlePlugMax_Example' do
  pod 'MKBlePlugMax', :path => '../'

  target 'MKBlePlugMax_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
